### ISSUE TITLE
introduce basic automations

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#256]
## Context

Lix apps and users want automations. 

![Image](https://github.com/user-attachments/assets/23b06480-5209-4d98-9b1f-4bc305688dc5)

## Proposal 

Offer basic automations that

- [ ] enables devs to ship apps with default automations
- [ ] users to adjust automation via a UI
- [ ] can run JavaScript actions to allow for arbitrary automation possibilities 

### Example use case of machine translating new variants

1. Create a `machine-translate/lix.automation.yml` file

- yml for multi line strings
- `lix.automation.yml` to query automation files via `**/lix.automation.yml`
- actions with different types to offer other types of actions in the future 

```yml
name: machine translate new variants

trigger:
  table: change
  type: AFTER INSERT
  condition: |
    NEW.schema_key = 'variant'

action:
  type: execute-javascript
  script: ./action.js
  args:
    change: NEW
```

2. create the `/machine-translate/action.js` file

```js
export async function run({ lix, change }) {
  const snapshot = await lix.db
    .selectFrom("snapshot")
    .where("id", "=", change.snapshot_id)
    .selectAll()
    .executeTakeFirstOrThrow();

  const translated = await machineTranslate(snapshot.content.pattern);

  return await createChange({
    lix,
    ...change,
    authors: ["machine-translate-automation"],
    snapshotContent: { ...snapshot.content, pattern: translated },
  });
}
```
