### ISSUE TITLE
introduce notification system

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#257]
## Context

Lix apps want a notification system. 

And what are notifications? Notifications are ... the outcome of a change. Given that notifications are an outcome of changes, lix can easily offer a notification system for lix apps and lix users. 

![Image](https://github.com/user-attachments/assets/d5d98b53-12b7-44fa-b42f-a95f68a08c7c)

## Proposal 

Offer a notification system. 

- [ ] configurable by users/app developers 
- [ ] triggered based on changes
- [ ] ideally inbox zero capability

**Comment by samuelstroschein** [comment]
### A simple solution via [#256 basic automations](https://github.com/opral/lix-sdk/issues/256)

1. Lix has a notification table 

```sql
CREATE TABLE notification (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  account_id TEXT NOT NULL DEFAULT ACTIVE_ACCOUNT,  -- Who receives the notification
  change_set_id TEXT NOT NULL,  -- Which change set triggered the notification
  message TEXT NOT NULL,  -- Notification content
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Timestamp of creation
  is_read BOOLEAN DEFAULT FALSE,  -- Whether the notification has been read
  is_archived BOOLEAN DEFAULT FALSE,  -- Whether the notification has been archived
  FOREIGN KEY (account_id) REFERENCES account(id),
  FOREIGN KEY (change_set_id) REFERENCES change_set(id)
);
```

2. User (or developer offering an app) creates a "notification" automation

```diff
 - lix/
  - notifications/
+    - machine-translation/lix.automation.yml
 
 - example.txt
```

```yml
name: get notified about new machine translations

trigger:
  table: change
  type: AFTER INSERT
  condition: |
    NEW.schema_key = 'variant'
    AND EXISTS (
      SELECT 1 FROM change_author
      WHERE change_author.change_id = NEW.id
      AND change_author.author = 'machine-translate-automation'
    )

action:
  type: insert
  table: notification
  values:
    message: "New machine translation added for change {{ NEW.id }}"
    change_set_id: CREATE_CHANGE_SET([NEW.id])
    created_at: CURRENT_TIMESTAMP
```
